spring:
  application:
    name: myPos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.23:3306/ormtest?serverTimezone=UTC
    show_sql: true
    username: root
    password: root
      #temporary data storage
      #jdbc: h2:mem:testdb
      #jdbc: h2:file:/data/sample
      #jdbc: h2:file:C:/data/sample (Windows only)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: create-drop
  autoconfigure:
  #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  logging:
    config: ./mypos/src/main/resources/log4j2.xml
server:
  port: 9000


