#https://docs.spring.io/autorepo/docs/spring-boot/2.2.6.RELEASE/reference/html/appendix-application-properties.html#core-properties
spring:
  application:
    name: myPos
  main:
    web-environment: false
    show_banner: false
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.23:3306/ormtest?useSSL=false&serverTimezone=UTC
    show_sql: true
    username: root
    password: root
    initialization-mode: always
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  autoconfigure:
  #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  logging:
    config: ./mypos/src/main/resources/log4j2.xml

fxml:
  main-panels:
    common-width: 1000
